---
- name: my first play
  hosts: all
  tasks:
    - name: play my hosts
      ping:
    - name: print message
      debug:
        var: ansible_facts
    - name: install nginx
      yum:
        name: nginx
        state: installed
      become: true
    - name: start nginx
      service:
        name: nginx
        state: started
      become: true
